"""migracao_inicial

Revision ID: 701c811f8af8
Revises: 
Create Date: 2026-08-03 14:17:05.463534
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '701c811f8af8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('localizacao', sa.String(length=200), nullable=False),
    sa.Column('fabricante', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('leituras_sensores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipamento_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dados', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordens_servico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipamento_id', sa.UUID(), nullable=False),
    sa.Column('usuario_abertura_id', sa.UUID(), nullable=True),
    sa.Column('usuario_responsavel_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('severidade', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('diagnostico_ml', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_abertura_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ordem_servico_id', sa.UUID(), nullable=True),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('equipamento_tipo', sa.String(length=50), nullable=False),
    sa.Column('passos', sa.JSON(), nullable=False),
    sa.Column('ferramentas', sa.JSON(), nullable=True),
    sa.Column('epi_obrigatorio', sa.JSON(), nullable=True),
    sa.Column('tempo_estimado_minutos', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('ordem_servico_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pops')
    op.drop_table('ordens_servico')
    op.drop_table('leituras_sensores')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('equipamentos')
    # ### end Alembic commands ###